spring:
  application:
    name: us-backend
  cassandra:
    keyspace-name: url_shortener
    contact-points: ${CASSANDRA_CONTACT_POINTS:127.0.0.1}
    port: ${CASSANDRA_PORT:9042}
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8080